const hubspot = require('@hubspot/api-client');

/**
 * Initialize HubSpot client with API key from environment
 */
function getHubSpotClient() {
  // Try process.env first (from .env file), then fall back to Firebase config
  const apiKey = process.env.HUBSPOT_API_KEY ||
                 (typeof require !== 'undefined' && require('firebase-functions').config?.()?.hubspot?.api_key);
  if (!apiKey) {
    throw new Error('HUBSPOT_API_KEY not found in environment variables or Firebase config');
  }
  console.log('🔑 HubSpot API key found, length:', apiKey.length);
  return new hubspot.Client({ accessToken: apiKey });
}

/**
 * Create or update a contact in HubSpot
 * @param {Object} contactData - Contact information
 * @param {string} contactData.email - Contact email (required)
 * @param {string} contactData.firstName - Contact first name
 * @param {string} contactData.lastName - Contact last name
 * @param {string} contactData.phone - Contact phone number
 * @param {Object} contactData.customProperties - Additional custom properties
 * @return {Promise<Object>} Created or updated contact
 */
async function createOrUpdateContact(contactData) {
  const hubspotClient = getHubSpotClient();

  const properties = {
    email: contactData.email,
  };

  if (contactData.firstName) properties.firstname = contactData.firstName;
  if (contactData.lastName) properties.lastname = contactData.lastName;
  if (contactData.phone) properties.phone = contactData.phone;

  // Add any custom properties
  if (contactData.customProperties) {
    Object.assign(properties, contactData.customProperties);
  }

  try {
    // Try to create the contact
    const response = await hubspotClient.crm.contacts.basicApi.create({
      properties,
      associations: []
    });
    console.log('✅ Contact created in HubSpot:', response.id);
    return response;
  } catch (error) {
    // If contact already exists (409 conflict), update it
    if (error.statusCode === 409) {
      console.log('Contact already exists, updating...');
      const existingContactId = error.body.message.match(/Existing ID: (\d+)/)?.[1];

      if (existingContactId) {
        const updateResponse = await hubspotClient.crm.contacts.basicApi.update(
          existingContactId,
          { properties }
        );
        console.log('✅ Contact updated in HubSpot:', existingContactId);
        return updateResponse;
      }
    }
    throw error;
  }
}

/**
 * Create a deal in HubSpot
 * @param {Object} dealData - Deal information
 * @param {string} dealData.dealName - Deal name (required)
 * @param {string} dealData.dealStage - Deal stage
 * @param {number} dealData.amount - Deal amount
 * @param {string} dealData.pipeline - Pipeline ID
 * @param {string} dealData.contactId - Associated contact ID
 * @param {Object} dealData.customProperties - Additional custom properties
 * @return {Promise<Object>} Created deal
 */
async function createDeal(dealData) {
  const hubspotClient = getHubSpotClient();

  const properties = {
    dealname: dealData.dealName,
  };

  if (dealData.dealStage) properties.dealstage = dealData.dealStage;
  if (dealData.amount) properties.amount = dealData.amount.toString();
  if (dealData.pipeline) properties.pipeline = dealData.pipeline;
  if (dealData.closeDate) properties.closedate = dealData.closeDate;

  // Add any custom properties
  if (dealData.customProperties) {
    Object.assign(properties, dealData.customProperties);
  }

  const associations = [];

  // Associate with contact if provided
  if (dealData.contactId) {
    associations.push({
      to: { id: dealData.contactId },
      types: [{
        associationCategory: 'HUBSPOT_DEFINED',
        associationTypeId: 3 // Deal to Contact association
      }]
    });
  }

  const response = await hubspotClient.crm.deals.basicApi.create({
    properties,
    associations
  });

  console.log('✅ Deal created in HubSpot:', response.id);
  return response;
}

/**
 * Create a property calculation note/engagement in HubSpot
 * @param {Object} noteData - Note information
 * @param {string} noteData.contactId - Associated contact ID
 * @param {string} noteData.propertyAddress - Property address
 * @param {string} noteData.strategy - Investment strategy
 * @return {Promise<Object>} Created note
 */
async function createPropertyNote(noteData) {
  const hubspotClient = getHubSpotClient();

  const noteBody = `
📍 Property Analysis: ${noteData.propertyAddress || 'N/A'}

Strategy: ${noteData.strategy || 'N/A'}

Generated by CloudCalcs on ${new Date().toLocaleString()}
`;

  const properties = {
    hs_timestamp: Date.now().toString(),
    hs_note_body: noteBody,
  };

  const associations = [];

  if (noteData.contactId) {
    associations.push({
      to: { id: noteData.contactId },
      types: [{
        associationCategory: 'HUBSPOT_DEFINED',
        associationTypeId: 202 // Note to Contact association
      }]
    });
  }

  const response = await hubspotClient.crm.objects.notes.basicApi.create({
    properties,
    associations
  });

  console.log('✅ Property note created in HubSpot:', response.id);
  return response;
}

/**
 * Search for a contact by email
 * @param {string} email - Contact email
 * @return {Promise<Object|null>} Contact object or null if not found
 */
async function findContactByEmail(email) {
  const hubspotClient = getHubSpotClient();

  try {
    const response = await hubspotClient.crm.contacts.searchApi.doSearch({
      filterGroups: [{
        filters: [{
          propertyName: 'email',
          operator: 'EQ',
          value: email
        }]
      }],
      properties: ['email', 'firstname', 'lastname', 'phone'],
      limit: 1
    });

    if (response.results && response.results.length > 0) {
      console.log('✅ Contact found in HubSpot:', response.results[0].id);
      return response.results[0];
    }

    console.log('ℹ️ Contact not found in HubSpot for email:', email);
    return null;
  } catch (error) {
    console.error('Error searching for contact:', error);
    throw error;
  }
}

/**
 * Create a property calculation event for a contact
 * Combines contact creation/update and note creation
 * @param {Object} eventData - Event data
 * @param {string} eventData.email - Contact email
 * @param {string} eventData.firstName - Contact first name
 * @param {string} eventData.lastName - Contact last name
 * @param {string} eventData.address - Property address
 * @param {string} eventData.method - Investment strategy/method
 * @return {Promise<Object>} Event creation result
 */
async function trackPropertyCalculation(eventData) {
  try {
    // Find or create contact
    let contact = await findContactByEmail(eventData.email);

    if (!contact) {
      contact = await createOrUpdateContact({
        email: eventData.email,
        firstName: eventData.firstName,
        lastName: eventData.lastName,
        phone: eventData.phone
      });
    }

    // Create note with calculation details (only address and method)
    const note = await createPropertyNote({
      contactId: contact.id,
      propertyAddress: eventData.address,
      strategy: eventData.method
    });

    return {
      success: true,
      contact: contact,
      note: note
    };
  } catch (error) {
    console.error('Error tracking property calculation:', error);
    throw error;
  }
}

module.exports = {
  getHubSpotClient,
  createOrUpdateContact,
  createDeal,
  createPropertyNote,
  findContactByEmail,
  trackPropertyCalculation
};
