// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jncqlvohqxzxjtfaqgfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuY3Fsdm9ocXh6eGp0ZmFxZ2ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDM5NzMsImV4cCI6MjA2OTU3OTk3M30.v9yMKbvlBFskMY3Ilay-oIDYcgmmVNSNIfQwwT2nXXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});