export const STRATEGY_TYPES = {
  FIX_AND_FLIP: 'Fix & Flip',
  ADD_ON: 'Add-On',
  ADU: 'ADU',
  NEW_BUILD: 'New Build',
  RENTAL: 'Rental'
} as const;

export const ADU_CONSTRAINTS = {
  MIN_LOT_SIZE_SQFT: 5000,
  MIN_HOUSE_SIZE_SQFT: 1500,
  MAX_HOUSE_TO_LOT_RATIO: 2.25,
  MULTI_STORY_FOOTPRINT_DIVISOR: 1.5,
  SETBACK_PERCENTAGE: 0.15,
  REQUIRED_ADU_SPACE_SQFT: 800
} as const;

export const CALCULATION_DEFAULTS = {
  IMPROVEMENT_FACTOR: 1.0,
  SIZE_FILTER_MIN_RATIO: 0.7,
  SIZE_FILTER_MAX_RATIO: 1.5,
  CONSTRUCTION_COST_PER_SQFT: 200,
  PERMIT_COSTS: 15000,
  DEFAULT_APPRECIATION_RATE: 0.03
} as const;

export const CACHE_SETTINGS = {
  DEFAULT_TTL_SECONDS: 3600,
  COMPS_TTL_SECONDS: 7200,
  RENT_DATA_TTL_SECONDS: 1800
} as const;